{% set name = "plotnine" %}
{% set version = "0.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "aae2c8164abb209ef4f28cab01132d23f6879fcf8d492657487359e1241459e5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python >=3.6.0
    - pip

  run:
    - python >=3.6.0
    - mizani >=0.6.0
    - matplotlib >=3.1.1
    - numpy >=1.16.0
    - scipy >=1.2.0
    - patsy >=0.4.1
    - statsmodels >=0.9.0
    - pandas >=0.25.0
    # - geopandas >=0.3.0
    - descartes >=1.1.0

test:
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.tests
    - plotnine.themes

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: GPL 2.0
  license_family: GPL2
  summary: 'A grammar of graphics for python'
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
