{% set name = "plotnine" %}
{% set version = "0.14.5" %}
{% set sha256 = "9e75969e8e10d8d770a4be36d10e075cc10b88ca6fcc99e36ada53436fb5653f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=59
    - wheel
    - setuptools-scm >=6.4
  run:
    - python
    - matplotlib-base >=3.8.0
    - pandas >=2.2.0
    - mizani >=0.13.0,<0.14.dev0
    - numpy >=1.23.5
    - scipy >=1.8.0
    - statsmodels >=0.14.0
  run_constrained:
    - adjusttext >=1.2.0
    - geopandas >=1.0.0
    - scikit-learn >1.2.0
    - scikit-misc >=0.5.1

test:
  requires:
    - pip
    - pytest
    - pytest-cov
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.mapping
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.themes
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pip check
    - pytest tests -vv

about:
  home: https://github.com/has2k1/plotnine
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A grammar of graphics for python
  description: |
    plotnine is an implementation of a grammar of graphics in Python based on ggplot2.
    The grammar allows you to compose plots by explicitly mapping variables in a dataframe to the visual objects that make up the plot.
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
