{% set name = "plotnine" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8dc491f5000062f6af7cf29429ee78b617daa8b2c22a1dd4e8b593f08bb51c20

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=59
    - wheel
    - setuptools-scm >=6.4
    - tomli
  run:
    - python
    - matplotlib-base >=3.8.0
    - pandas >=2.2.0
    - mizani >=0.14.0,<0.15
    - numpy >=1.23.5
    - scipy >=1.8.0
    - statsmodels >=0.14.5
  run_constrained:
    - adjusttext >=1.2.0
    - geopandas >=1.0.0
    - geodatasets >=2024.8.0
    - scikit-learn >=1.3.0
    - scikit-misc >=0.5.1
    - polars >=1.24.0
    - pyarrow >=19.0.1
    - pyright >=1.1.403

test:
  imports:
    - plotnine
    - plotnine._mpl.patches
    - plotnine._mpl.utils
    - plotnine._utils
    - plotnine._utils.yippie
    - plotnine.animation
    - plotnine.composition
    - plotnine.data
    - plotnine.doctools
    - plotnine.exceptions
    - plotnine.facets
    - plotnine.geoms.geom
    - plotnine.ggplot
    - plotnine.helpers
    - plotnine.layer
    - plotnine.mapping.aes
    - plotnine.options
    - plotnine.positions.position
    - plotnine.scales
    - plotnine.scales.scale_alpha
    - plotnine.scales.scale_linetype
    - plotnine.scales.scale_shape
    - plotnine.scales.scale_size
    - plotnine.scales.scale_xy
    - plotnine.scales.scales
    - plotnine.stats.binning
    - plotnine.stats.stat
    - plotnine.stats.stat_ellipse
    - plotnine.themes.theme
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # E assert images not close
    # pstream issue https://github.com/has2k1/plotnine/issues/627
    # https://github.com/conda-forge/plotnine-feedstock/blob/main/recipe/meta.yaml#L67
    # - pytest -v tests

about:
  home: https://github.com/has2k1/plotnine
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: A grammar of graphics for python
  description: |
    plotnine is an implementation of a grammar of graphics in Python based on ggplot2.
    The grammar allows you to compose plots by explicitly mapping variables in a dataframe to the visual objects that make up the plot.
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
