{% set name = "plotnine" %}
{% set version = "0.2.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c461392d408a168b6a2160b1014c732d34fa1c0d4f642dc6c7ebc171173b74e9" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six
    - mizani >=0.3.1
    - matplotlib >=2.0.0
    - numpy
    - scipy
    - patsy >=0.4.1
    - statsmodels >=0.8.0
    - pandas >=0.20.1

test:
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.tests
    - plotnine.themes

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: GPL 2.0
  license_family: GPL2
  summary: 'A grammar of graphics for python'
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
