{% set name = "plotnine" %}
{% set version = "0.9.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "0e89a93015f3c71d6844ac7aa9fb0da09b908f5f7dfa7dd5d68a5ca32b2ebcea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8.0
    - pip

  run:
    - python >=3.8.0
    - mizani >=0.7.3
    - matplotlib-base >=3.5.0
    - numpy >=1.19.0
    - scipy >=1.5.0
    - patsy >=0.5.1
    - statsmodels >=0.13.2
    - pandas >=1.3.5
    # - geopandas >=0.3.0

test:
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.mapping
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.themes

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  summary: A grammar of graphics for python
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
