{% set name = "plotnine" %}
{% set version = "0.13.6" %}
{% set sha256 = "3c8c8f958c295345140230ea29803488f83aba9b5a8d0b1b2eb3eaefbf0a06b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - matplotlib-base >=3.7.0
    - pandas >=2.1.0,<3.0a0
    - mizani >=0.11.0,<0.12.0
    - numpy >=1.23.0
    - scipy >=1.7.0
    - statsmodels >=0.14.0
  run_constrained:
    - scikit-misc >=0.3.0

test:
  requires:
    - pip
    - pytest
    - pytest-cov
    # geopandas isn't available on s390x
    - geopandas  # [py<310 and not (linux and s390x)]
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.mapping
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.themes
  source_files:
    - tests
    - "pyproject.toml"
  commands:
    # Disable pip check because of mizani 0.9.2 requires tzdata, which is not installed,
    # see also https://github.com/AnacondaRecipes/mizani-feedstock/pull/3#issue-1812052144
    - pip check
    # Disable pytest because a lot of tests has an error 'assert images not close',
    # see the upstream issue https://github.com/has2k1/plotnine/issues/627
    # conda-forge also disables pytest https://github.com/conda-forge/plotnine-feedstock/commit/5d559dbd9a09b83cd74a55ea11587cbff29eef64
    #- pytest tests -vv

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  license_family: MIT
  summary: A grammar of graphics for python
  description: |
    plotnine is an implementation of a grammar of graphics in Python based on ggplot2.
    The grammar allows you to compose plots by explicitly mapping variables in a dataframe to the visual objects that make up the plot.
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
