travis:
  secure:
    BINSTAR_TOKEN: ONl/CIeQWdhfre4EaVWLUvVvYrt1bZej8CuQMD9lCZKEn7mRW3PG8J+TbNbnq3yogXgMZnwh9rWSIBH4JyeiqmdPdbZGvxUFMn6VNjr0tQC3gJU/O2fGzH8D98QV3+F8myrJ2utsDhnTleeuEMyDIQcX8nz/1DBZOZlgV2ougTxzSHw+UO/vHQMZlv/K5wh70kLs0tYf/U1vHR+eogOYBD4W9T5WT9xHM7WZCQQgmm5r/u5EGJz+B+XPajt12hJMBrqyub0OmzgqPlim8RyUFkQL77M1YH04fW/PAhmCLGDzGulhnXS0My5OMnYQSO2sDvUwBXz0GfwOP7RTcvkkl5gF5Li2K/8l5u3/Tsu0LTGdaIy1+ANI0BBF5z9fcvsR+YwU+EcKkpRmDFKixv1emNLw+aQ8bAZad6ytUXDtNyPL2Erd9iAtiXqSxICvQg1+hRRl8XUUKmEjzGIWFxDHSvwLCb2rx+PjrPWhGynjvNM92zlo0qafGTVdpSLv44EmqL4ZHurhv4rJ+y7EMFQF4HUkj3rPClvfYK9yoHEv64O7lHp3CrJMwLIU2EJlNvvMtSXn6XA6UCSPrt65uWQFrj33gRV5wFIofqjiDsTEVIF3vhYzosU9QNaIghebADtaeBFYYN8hcxz8y4pq13ToPcVWOCA2/YtWmdGFT8TTVq4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
