travis:
  secure:
    BINSTAR_TOKEN: Td2fFqRzxUmBlnI+21lt3dWbNZSkRN/nFJ/8WL8rAUWFB4YiWJ90einJSJ/QUUhibNuNLA6SvpVQfAgM1FfFpvRL7hr6xyJzXoJP75te4Y8/Jwa2oPUGVej8TNJW9XMV8ZkpmPh9JpGXEZIuM6yyZDxZEOaGuK3f/7OqLOK1kkZ82a7jvc9Vw+934V4FxFP8LEgZjnO7IpwgoTAdPZkT7W2le2taJQyvh0rIrde3k45rMQHk97CyNz7P7CELAT/srFf+EtzSrievK1UvpJCspCDjhUmVO3NDzyxIzZfKEfkDSOFqSBcMmmwQCYwzUIDFQCVkiuGe7Xf1d32CQGoNf/2cXXvfMmG942ywBOlemRW1KlR3Y3HWmDPzhxV7hYPX6f8U3c4kqhrbSyVVPpiH1cLNTbMNdBApDzNGdngA247lm5OSTncD9WCCMcqhArdWBXKvq2MQ0zq3VfHt3CB0hk9dXAaMt5usowGcJIGGrMpByWK3qOG0QwGwT1mRKfxsmt0X/O1mGRig9P7spzyK2+dJE1o3polGkfZfdDdPnsLcafdkMdgokZFQC3FrnLVWXxk+4e7vHnNEUa2LfKQbFylxq9rRR8IEMtIt9bEPiB+ex9WdrMG/T4NtadMTGpfkRNWJsnhv3/FTQnqABELldjUchAuNxzPSvv6VAT041+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
