travis:
  secure:
    BINSTAR_TOKEN: cB1LEmDDqOiKbvSqTd80BJ/NHBkEcNxj2nsDXYbsXfKOslvYos58zuD97yud31jV9tkKwnDbI8BTDgK0sB+dDG+wiYsmh+S1uLiG/j0cksJYy/t+N4ZA4UHblOmowRTiio61dYB2rjJ1rFPmSpHVnpJqgwZk8K88d3En0u9d2XUyOUitNbW6y90vZ32LrvCvmcPFPa9qcivRcFsaKbp75xLCb2NgSYn4Nx/nzmfDXJgPB3TrayajYIkU2WtRpk1JltnB8HbIvvIIC7x5V2UAMeuBlaNZbVh+oVnc3hzjIpYxFf/vXzutTmMd2F0bU3fYKAIpdZFCL4ZyPDxY+YHDWv15pI75ri2TkHMRC40VSEvLsjpNRe0yCZUMKePNTlK20P6k/WvjuZmHUNaYg6O9KYS8fNdlsId175Ft+QUWc6nEnzl6pHhn7rPiHlVbpzxSUla6vRIZbzAL5Ldp1Iyue0Vh+NnvFBJSUN9rqhwocbrkSgJCx+3RkxJpUW7n+N+ZgOOLY6S9YRVOdlupAOgVuXTH7gMcGJKEHx3Ry78M7SjvlhYC0r3W4ASGFyyvfnU39pBFFlxcmLk4i/gQxtNE0y20HiLC45BRYBvvbts8Tf2vcmZkNN9THUP0045iSg7eyopvaDCjr5Q9BSXVaPEY+nStTY1l3+HjRKbQzFtVxA4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
