travis:
  secure:
    BINSTAR_TOKEN: eFu73DnqnI4GG2Zqou8tWZ8GU73JDE7h1PWzF+8DSVEV7tcInhh6xK4U9g2H4djiLMz0dZDqou1eR8X32N4nAti3wYibOqJuLPKNv8q9VNaGHBRTJvnog96hkk9ePy22vmW/VM4lE7E/yXP5EvDk6o2MOEPu2YhNd2nU9eAMKxoJLOL0X1x9I18njZkTr36rw4YhQVtgI2JczZbDlmF96lMTyvpHSHo07h1hMc5xGkMtppTcIkFAPcMwYhL3P9DiTRE/NSq97lmHOh3RotspPuV+f/WQjZ0D3hWcYgIgXiqKKm3LE7OOIG/Lq9mjyIsz2J60SApNoNZK8SfzH8WCDH4WBLFH7TY5LXytCC92zuHk9KrxJXpe6HmhGpBDu8aTtnDD365vt82mQ0y4XIoPoMdkEScNzFIGRwqnSs6y2I2vu6czBJ5F+UlKWI9WikDBXBB9D4Cjw/tIgrqX/p86Y/qakiXVZ7XbXtdDewYa9ymoXfFCxQUwMEcFcyYVHIhG5+amSikBZiZww+Q1ge1TxbWK/zDUVkp0ezcUjy4JcC22lh3nL9AiYNTWyFEncLNJlDwHt+KrOcn91w7q2GGbgnHKxV+sOnexWDtrwlOLp8VsRiuznNZLHtOZji3S+TgK6Np0ZmS6E5W47p6uTQ584VZESgk++Ww1GzLXR6NBMNY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
